version: '3.7'
services:
  # THIS SAYS TO HAVE A SERVICE CALLED APP
  app:

    # Service configuration
    build:
      # Setting the context to the current directory
      context: .
      # Specifying the dockerfile
      dockerfile: Dockerfile

    # Allows real-time project update
    volumes:
      - .:/code

    # Setting as true means we can interact with the container (i.e. open a bash shell)
    tty: true


    command: /bin/bash

# Defining the volumes
volumes:
  code:
